#!/usr/bin/env bash
#
# install-hypr-switch.sh
# Installer for hypr-switch — a symlink-based shell switcher for Hyprland.
# https://github.com/bobincraft1/hypr-switch
#
# hypr-switch itself auto-discovers shells from ~/.config/hypr/shells/ every
# time it runs, so this installer's only jobs are:
#   1. Install the hypr-switch command
#   2. Optionally generate skeleton configs for any shell names you pass in
#      that don't already have one
#
# Once installed, adding a new shell NEVER requires re-running this script —
# just `mkdir -p ~/.config/hypr/shells/<name>` and drop a hyprland.lua or
# hyprland.conf inside. hypr-switch will pick it up on the very next run.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHELLS_DIR="$HOME/.config/hypr/shells"
HYPR_DIR="$HOME/.config/hypr"
BIN_DIR="$HOME/.local/bin"
SCRIPT_PATH="$BIN_DIR/hypr-switch"
LOCK_CMD='~/.local/share/quickshell-lockscreen/lock.sh'
TERMINAL_CMD='kitty'

echo "== hypr-switch installer =="

mkdir -p "$SHELLS_DIR" "$BIN_DIR"

# --- 1. Install the standalone hypr-switch script as-is ---
if [[ -f "$SCRIPT_DIR/hypr-switch" ]]; then
    cp "$SCRIPT_DIR/hypr-switch" "$SCRIPT_PATH"
    chmod +x "$SCRIPT_PATH"
    echo "[1/3] Installed hypr-switch to $SCRIPT_PATH"
else
    echo "ERROR: hypr-switch script not found next to this installer (expected: $SCRIPT_DIR/hypr-switch)" >&2
    exit 1
fi

# --- 2. Detect uwsm, purely to choose the right skeleton exit keybind text ---
if command -v uwsm >/dev/null 2>&1 && pgrep -x uwsm >/dev/null 2>&1; then
    EXIT_LUA_LINE='hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("uwsm stop"), { description = "Logout" })'
    EXIT_CONF_LINE='bind = SUPER SHIFT, E, exec, uwsm stop'
else
    EXIT_LUA_LINE='hl.bind("SUPER + SHIFT + E", hl.dsp.exit(), { description = "Logout" })'
    EXIT_CONF_LINE='bind = SUPER SHIFT, E, exit,'
fi
echo "[2/3] Detected session type, skeleton exit keybind chosen."

# --- 3. Optionally generate skeleton configs for any shell names passed in ---
if [[ $# -eq 0 ]]; then
    echo "[3/3] No shell names passed — skipping skeleton generation."
    echo ""
    echo "== Install complete =="
    echo "hypr-switch is installed and will auto-discover any shells already"
    echo "present in $SHELLS_DIR"
    echo ""
    echo "To add a shell right now:"
    echo "  mkdir -p $SHELLS_DIR/<name>"
    echo "  cp /path/to/your/hyprland.lua $SHELLS_DIR/<name>/hyprland.lua"
    echo ""
    echo "Then activate it with:"
    echo "  hypr-switch <name>"
    exit 0
fi

SHELL_NAMES=("$@")
echo "[3/3] Processing shell names: ${SHELL_NAMES[*]}"

for shell in "${SHELL_NAMES[@]}"; do
    dir="$SHELLS_DIR/$shell"
    mkdir -p "$dir"

    lua_file="$dir/hyprland.lua"
    conf_file="$dir/hyprland.conf"

    if [[ -f "$lua_file" ]]; then
        filetype="hyprland.lua"
        echo "  [$shell] Existing hyprland.lua found — will inject keybinds if missing."
    elif [[ -f "$conf_file" ]]; then
        filetype="hyprland.conf"
        echo "  [$shell] Existing hyprland.conf found — will inject keybinds if missing."
    else
        echo ""
        echo "  No config found for '$shell'."
        read -rp "    Generate a new one as .lua or .conf? [lua/conf]: " answer
        case "$answer" in
            conf) filetype="hyprland.conf" ;;
            *)    filetype="hyprland.lua" ;;
        esac
    fi

    target="$dir/$filetype"

    if [[ ! -f "$target" ]]; then
        if [[ "$filetype" == "hyprland.lua" ]]; then
            cat > "$target" << SKEL
-- Minimal hyprland.lua skeleton for shell: $shell
-- Generated by install-hypr-switch.sh

monitor = { }

-- Keybinds
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("hypr-switch"), { description = "Switch Hyprland shell" })
hl.bind("SUPER + T", hl.dsp.exec_cmd("$TERMINAL_CMD"), { description = "Open terminal" })
hl.bind("SUPER + L", hl.dsp.exec_cmd("$LOCK_CMD"), { description = "Lock screen" })
$EXIT_LUA_LINE

-- Add your window rules, animations, and layout config below
SKEL
        else
            cat > "$target" << SKEL
# Minimal hyprland.conf skeleton for shell: $shell
# Generated by install-hypr-switch.sh

monitor=,preferred,auto,1

# Keybinds
bind = SUPER SHIFT, S, exec, hypr-switch
bind = SUPER, T, exec, $TERMINAL_CMD
bind = SUPER, L, exec, $LOCK_CMD
$EXIT_CONF_LINE

# Add your window rules, animations, and layout config below
SKEL
        fi
        echo "  [$shell] Generated new $filetype with keybinds pre-installed (including SUPER+T for terminal)."
    else
        # File exists already — inject only missing keybinds, never overwrite.
        if [[ "$filetype" == "hyprland.lua" ]]; then
            grep -q 'exec_cmd("hypr-switch")' "$target" || \
                echo "hl.bind(\"SUPER + SHIFT + S\", hl.dsp.exec_cmd(\"hypr-switch\"), { description = \"Switch Hyprland shell\" })" >> "$target"
            grep -qE 'exec_cmd\("(kitty|alacritty|foot|wezterm|konsole|gnome-terminal)"' "$target" || \
                echo "hl.bind(\"SUPER + T\", hl.dsp.exec_cmd(\"$TERMINAL_CMD\"), { description = \"Open terminal\" })" >> "$target"
            grep -qF "$LOCK_CMD" "$target" || \
                echo "hl.bind(\"SUPER + L\", hl.dsp.exec_cmd(\"$LOCK_CMD\"), { description = \"Lock screen\" })" >> "$target"
            grep -q 'hl.dsp.exit()\|uwsm stop' "$target" || \
                echo "$EXIT_LUA_LINE" >> "$target"
        else
            grep -q 'exec, hypr-switch' "$target" || \
                echo "bind = SUPER SHIFT, S, exec, hypr-switch" >> "$target"
            grep -qE 'exec, (kitty|alacritty|foot|wezterm|konsole|gnome-terminal)' "$target" || \
                echo "bind = SUPER, T, exec, $TERMINAL_CMD" >> "$target"
            grep -qF "$LOCK_CMD" "$target" || \
                echo "bind = SUPER, L, exec, $LOCK_CMD" >> "$target"
            grep -q 'exit,\|uwsm stop' "$target" || \
                echo "$EXIT_CONF_LINE" >> "$target"
        fi
        echo "  [$shell] Injected any missing keybinds into existing $filetype (nothing overwritten)."
    fi
done

if command -v fish >/dev/null 2>&1; then
    fish -c "fish_add_path $BIN_DIR" 2>/dev/null || true
fi

echo ""
echo "== Install complete =="
echo "Script location: $SCRIPT_PATH"
echo "Configured shells: ${SHELL_NAMES[*]}"
echo ""
echo "Create the initial active symlink with:"
echo "  hypr-switch ${SHELL_NAMES[0]}"
echo ""
echo "Remember: to add MORE shells later, you do NOT need to run this"
echo "installer again. Just create the folder and drop a config in it:"
echo "  mkdir -p $SHELLS_DIR/<name>"
echo "  cp /path/to/hyprland.lua $SHELLS_DIR/<name>/hyprland.lua"
echo "hypr-switch will discover it automatically on its next run."